@tool
extends RichTextLabel

@export var input_text = "a" :
	set(v):
		input_text = v
		render_icon()

func _ready():
	render_icon()

func render_icon():
	if input_text == null or input_text == "":
		return

	var ei_key = keymap.get(input_text)
	var ei_key_extra = keymap_extra.get(input_text)

	if ei_key:
		text = "%s" % ei_key
	elif ei_key_extra:
		# our bold font is the enter_input_extra variant
		text = "[b]%s[/b]" % ei_key_extra
	else:
		Log.warn("No key found for input", input_text)
		return

var keymap = {
	"A"="a",
	"B"="b",
	"C"="c",
	"D"="d",
	"E"="e",
	"F"="f",
	"G"="g",
	"H"="h",
	"I"="i",
	"J"="j",
	"K"="k",
	"L"="l",
	"M"="m",
	"N"="n",
	"O"="o",
	"P"="p",
	"Q"="q",
	"R"="r",
	"S"="s",
	"T"="t",
	"U"="u",
	"V"="v",
	"W"="w",
	"X"="x",
	"Y"="y",
	"Z"="z",
	"0"="0",
	"1"="1",
	"2"="2",
	"3"="3",
	"4"="4",
	"5"="5",
	"6"="6",
	"7"="7",
	"8"="8",
	"9"="9",
	"!"="!",
	"\""="\"",
	"#"="#",
	"$"="$",
	"%"="%",
	"&"="&",
	"'"="'",
	"("="(",
	")"=")",
	"*"="*",
	"+"="+",
	","=",",
	"-"="-",
	"."=".",
	"/"="/",
	":"=":",
	";"=";",
	"<"="<",
	"="="=",
	">"=">",
	"?"="?",
	"["="[",
	"]"="]",
	"\\"="\\",
	"^"="^",
	"_"="_",
	"`"="`",
	"{"="{",
	"}"="}",
	"|"="|",
	"~"="~",
	"@"="@",
	"Ctrl"="C",
	"Scroll Lock"="L",
	"Esc"="R",
	"Alt"="A",
	"Tab"="T",
	"Menu"="M",
	"Super"="W",
	"Backspace"="B",
	"Enter"="E",
	"Shift"="S",
	"Print Screen"="P",
	"End"="N",
	"Delete"="D",
	"Insert"="I",
	"Home"="H",
	"Caps Lock"="O",
	"Pause"="U",
	"Page Up"="K",
	"Page Down"="J",
	"Up Arrow"="G",
	"Down Arrow"="F",
	"Left Arrow"="V",
	"Right Arrow"="Q",
	"Space Bar"="Z",
	}


var keymap_extra={
	"f1"="1",
	"f2"="2",
	"f3"="3",
	"f4"="4",
	"f5"="5",
	"f6"="6",
	"f7"="7",
	"f8"="8",
	"f9"="9",
	"f10"="0",
	"f11"="(",
	"f12"=")",
	"Mouse"="M",
	"Mouse Left Click"="L",
	"Mouse Right Click"="R",
	"Mouse Scroll"="S",
	"A Button"="A",
	"B Button"="B",
	"X Button"="X",
	"Y Button"="Y",
	"Square Button"="N",
	"Triangle Button"="T",
	"Circle Button"="C",
	"Dpad"="D",
	"Dpad Up"="^",
	"Dpad down"="V",
	"Dpad left"="<",
	"Dpad right"=">",
	"Left Button"="Q",
	"Right Button"="W",
	"Left Trigger"="O",
	"Right Trigger"="P",
	"Arcade stick up left"="q",
	"Arcade stick up"="w",
	"Arcade stick up right"="e",
	"Arcade stick left"="a",
	"Arcade stick neutral"="s",
	"Arcade stick right"="d",
	"Arcade stick down left"="z",
	"Arcade stick down"="x",
	"Arcade stick down right"="c",
	"Arcade stick 'L'"="[",
	"Arcade stick 'R'"="]",
	"Joystick up left"="r",
	"Joystick up"="t",
	"Joystick up right"="y",
	"Joystick left"="f",
	"Joystick neutral"="g",
	"Joystick right"="h",
	"Joystick down left"="v",
	"Joystick down"="b",
	"Joystick down right"="n",
	"Joystick 'L'"="{",
	"Joystick 'R'"="}",
	}
