#+title: Dot Hop
#+startup: overview

* _
#+html: <div id="header" align="center">
#+html: <div id="badges">
#+html:   <a href="https://mastodon.gamedev.place/@russmatney">
#+html:     <img src="https://img.shields.io/badge/Mastodon-teal?style=for-the-badge&logo=mastodon&logoColor=white" alt="Mastodon Badge"/>
#+html:   </a>
#+html:   <a href="https://www.twitch.tv/russmatney">
#+html:     <img src="https://img.shields.io/badge/Twitch-purple?style=for-the-badge&logo=twitch&logoColor=white" alt="Twitch Badge"/>
#+html:   </a>
#+html:   <a href="https://www.patreon.com/russmatney">
#+html:     <img src="https://img.shields.io/badge/Patreon-red?style=for-the-badge&logo=patreon&logoColor=white" alt="Patreon Badge"/>
#+html:   </a>
#+html:   <a href="https://discord.gg/xZHWtGfAvF">
#+html:     <img alt="Discord" src="https://img.shields.io/discord/758750490015563776?style=for-the-badge&logo=discord&logoColor=fff&label=discord" />
#+html:   </a>
#+html: </div>
#+html: </div>

* Dot Hop

Steam page coming soon!

* Copyright Notice
Dot Hop © 2023-2024 by Russell Matney is licensed under CC BY-NC-ND 4.0. To view a copy
of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/

That's ~Attribution Required~, ~No-Derivatives~, and ~Non-Commerical~ use only!

Dot Hop is 'Source Available' (as opposed to 'Open Source'). The code and some
assets are available for reference and educational purposes, but you cannot copy
and redistribute the game, the code, or the assets without explicit permission.

#+begin_quote
I'm in the process of breaking the addons and reusable parts of this codebase
out into properly licensed open source repos, so stay tuned!
#+end_quote

*** Note: Third-party assets in this repo must be purchased to use
Dot Hop uses third-party assets that must be purchased before they can be used
in your own projects!

Fonts:

- [[https://v3x3d.itch.io/arcade-cabinet][Arcade Cabinet by V3X3D]]
- [[https://v3x3d.itch.io/enter-input][Enter Input by V3X3D]]

These are available (after purchase) under the CC4 licence:
https://creativecommons.org/licenses/by/4.0/legalcode
